# Generated by Django 5.0.6 on 2024-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_rating_alter_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('sold_out', 'Sold Out'), ('unavailable', 'Unavailable')], default='in_stock', max_length=20),
        ),
    ]
