# Generated by Django 5.0.6 on 2024-07-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
